security:
  oauth2:
    client:
      client-id: LITSystem
      client-secret: LITSystem
      access-token-uri: http://www.login.liquorintransit.party/uaa/oauth/token
      grant-type: client_credentials
      scope: system
spring:
  jpa:
    hibernate:
      ddl-auto: create
  http:
    multipart:
      enabled: true
      
imgur:
  oauth2:
    resource:
      access-token-uri: https://api.imgur.com/oauth2/token
      grantType: password
      clientId: 30c968b8bef59b4
      clientSecret: 5ab2b7483e46068e8c5178d2da4ac010a008db44
      username: LiquorInTransit
      password: hbBmCGk5!
      
stripe:
  secret-key: sk_test_U0Y1OZCoDGrpLibNXdRcf6vO
  public-key: pk_test_gLfcfVLI76W77BncajD81v4w
      
      
---
   
spring:
  profiles: dev
security:
  oauth2:
    client:
      access-token-uri: http://localhost:5000/uaa/oauth/token
