zuul:
  sensitiveHeaders:
  routes:
    uaa-service:
      sensitiveHeaders:
      path: /api/users/**
      stripPrefix: false
    account-service:
      sensitiveHeaders:
      path: /api/accounts/**
      stripPrefix: false
    order-service:
      sensitiveHeaders:
      path: /api/orders/**
      stripPrefix: false

hystrix:
  command:
    uaa-service:
      execution:
        timeout:
          enabled: false
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
            

---

spring:
  profiles: dev
server:
  port: 8080
