zuul:
  sensitiveHeaders:
  routes:
    uaa-service:
      sensitiveHeaders:
      path: /api/users/**
      stripPrefix: false
    account-service:
      sensitiveHeaders:
      path: /api/accounts/**
      stripPrefix: false
    order-service:
      sensitiveHeaders:
      path: /api/orders/**
      stripPrefix: false
    shopping-cart-service:
      sensitiveHeaders:
      path: /api/cart/**
      stripPrefix: false
    product-service:
      sensitiveHeaders:
      path: /api/products/**
      stripPrefix: false
    delivery-service:
      sensitiveHeaders:
      path: /api/deliveries/**
      stripPrefix: false
    delivery-tracker:
      sensitiveHeaders:
      path: /api/tracking/**
      stripPrefix: false
  host:
    socket-timeout-millis: 10000
      

            

---

spring:
  profiles: dev
server:
  port: 8080
