zuul:
  sensitiveHeaders:
  routes:
    uaa-service:
      sensitiveHeaders:
      path: /api/users/**
      stripPrefix: false
    account-service:
      sensitiveHeaders:
      path: /api/accounts/**
      stripPrefix: false
    order-service:
      sensitiveHeaders:
      serviceId: order-and-delivery-service
      path: /api/orders/**
      stripPrefix: false
    shopping-cart-service:
      sensitiveHeaders:
      path: /api/cart/**
      stripPrefix: false
    product-service:
      sensitiveHeaders:
      serviceId: product-and-store-service
      path: /api/products/**
      stripPrefix: false
    delivery-service:
      sensitiveHeaders:
      serviceId: order-and-delivery-service
      path: /api/deliveries/**
      stripPrefix: false
    delivery-tracker:
      sensitiveHeaders:
      path: /api/tracking/**
      stripPrefix: false
    places-service:
      sensitiveHeaders:
      path: /api/places/**
      stripPrefix: false
    payment-service:
      sensitiveHeaders:
      path: /api/payments/**
      stripPrefix: false
  host:
    socket-timeout-millis: 10000
      

            

---
spring:
  profiles: dev
  thymeleaf:
    cache: false
server:
  port: 8080
