lcbo-client:
  url: https://www.lcboapi.com
  key: MDo1NDQwN2RjYy0wMDhkLTExZTctYWEwNy0yMzI4NjgxOTRjOWU6V2hSaDdoOXBVbjFjTU80cUtBZlpxRkI4UlJDVWcxRWlBUWZZ

spring:
  jpa:
    hibernate:
      ddl-auto: create
---
spring:
  profiles: dev 
  jpa:
    show-sql: false
