spring:
  jpa:
    hibernate:
      ddl-auto: create
security:
  oauth2:
    client:
      client-id: LITSystem
      client-secret: LITSystem
      access-token-uri: http://www.login.liquorintransit.party/uaa/oauth/token
      grant-type: client_credentials
      scope: system
      
stripe:
  secret-key: sk_test_U0Y1OZCoDGrpLibNXdRcf6vO
  public-key: pk_test_gLfcfVLI76W77BncajD81v4w

---

spring:
  profiles: dev
security:
  oauth2:
    client:
      access-token-uri: http://localhost:5000/uaa/oauth/token